# Generated by Django 3.0.6 on 2020-05-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('creation_date', models.TimeField(auto_now_add=True)),
                ('artist1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist1', to='artist.Artist')),
                ('artist2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist2', to='artist.Artist')),
            ],
        ),
    ]
